from __future__ import annotations

from pathlib import Path

from pyprideap.core import AffinityDataset
from pyprideap.qc.compute import (
    CorrelationData,
    CvDistributionData,
    DetectionRateData,
    DistributionData,
    LodAnalysisData,
    MissingFrequencyData,
    MissingValuesData,
    PcaData,
    QcLodSummaryData,
    compute_all,
)


def qc_report(dataset: AffinityDataset, output: str | Path) -> Path:
    """Generate a complete QC HTML report for the dataset."""
    try:
        import plotly  # noqa: F401
    except ImportError:
        raise ImportError("Plotly is required for HTML reports. Install with: pip install pyprideap[plots]") from None

    from pyprideap.qc import render as R

    output = Path(output)
    plot_data = compute_all(dataset)

    _RENDERERS = {
        "distribution": (DistributionData, R.render_distribution),
        "missing_frequency": (MissingFrequencyData, R.render_missing_frequency),
        "qc_summary": (QcLodSummaryData, R.render_qc_summary),
        "lod_analysis": (LodAnalysisData, R.render_lod_analysis),
        "pca": (PcaData, R.render_pca),
        "correlation": (CorrelationData, R.render_correlation),
        "missing_values": (MissingValuesData, R.render_missing_values),
        "cv_distribution": (CvDistributionData, R.render_cv_distribution),
        "detection_rate": (DetectionRateData, R.render_detection_rate),
    }

    sections: list[str] = []
    toc_items: list[str] = []

    for key, (_dtype, renderer) in _RENDERERS.items():
        data = plot_data.get(key)
        if data is None:
            continue
        fig = renderer(data)
        fig.update_layout(height=500)
        section_title = data.title
        section_id = key
        toc_items.append(f'<li><a href="#{section_id}">{section_title}</a></li>')
        plot_html = fig.to_html(full_html=False, include_plotlyjs=False, default_height="500px")
        sections.append(
            f'<div id="{section_id}" style="margin-bottom:40px;">'
            f"<h2>{section_title}</h2>"
            f"{plot_html}"
            f"</div>"
        )

    platform_label = dataset.platform.value.replace("_", " ").title()
    n_samples = len(dataset.samples)
    n_features = len(dataset.features)

    css_body = 'font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #fafafa;'  # noqa: E501
    css_summary = "background: white; padding: 15px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);"  # noqa: E501
    summary_p = f"<strong>Platform:</strong> {platform_label} | <strong>Samples:</strong> {n_samples} | <strong>Features:</strong> {n_features}"  # noqa: E501

    html = (
        "<!DOCTYPE html>\n<html>\n<head>\n"
        '    <meta charset="utf-8">\n'
        f"    <title>QC Report \u2014 {platform_label}</title>\n"
        '    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>\n'
        "    <style>\n"
        f"        body {{ {css_body} }}\n"
        "        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }\n"
        "        h2 { color: #34495e; }\n"
        f"        .summary {{ {css_summary} }}\n"
        "        nav ul { list-style: none; padding: 0; display: flex; flex-wrap: wrap; gap: 10px; }\n"
        "        nav a { color: #3498db; text-decoration: none; }\n"
        "        nav a:hover { text-decoration: underline; }\n"
        "    </style>\n</head>\n<body>\n"
        f"    <h1>QC Report &mdash; {platform_label}</h1>\n"
        '    <div class="summary">\n'
        f"        <p>{summary_p}</p>\n"
        "    </div>\n"
        f"    <nav><ul>{''.join(toc_items)}</ul></nav>\n"
        f"    {''.join(sections)}\n"
        '    <footer><p style="color:#999; font-size:0.85em;">Generated by pyprideap</p></footer>\n'
        "</body>\n</html>"
    )

    output.write_text(html)
    return output
